Cyn/warning
vega/vega-editor pull request #158
Opened 2017-06-16 23:29 UTC by starry97

1. Show warnings
2. Display warning/error pane

2017-06-17 02:28 UTC, domoritz commented
I'm getting errors as soon as I start the editor

<img width="610" alt="screen shot 2017-06-16 at 19 28 09" src="https://user-images.githubusercontent.com/589034/27249413-fcef4cc6-52c9-11e7-8849-955865f1a19a.png">

2017-06-17 17:35 UTC, starry97 commented
Weird. It works for me. Can you try to run it in incognito mode?

2017-06-23 05:49 UTC, domoritz commented
This looks awesome! I noticed one little glitch. When there was an error, there is not visualization. Then, when I correct the error, the visualization doesn't automatically update. Can you fix that?

![editor](https://user-images.githubusercontent.com/589034/27468134-e028c590-579c-11e7-833c-8ede792225c6.gif)

2017-06-23 05:49 UTC, domoritz commented
Another problem I noticed is that warnings from the editor are not shown.

<img width="1053" alt="screen shot 2017-06-22 at 22 48 53" src="https://user-images.githubusercontent.com/589034/27468161-082bef40-579d-11e7-8412-2f91e476f82b.png">

2017-06-23 05:51 UTC, domoritz commented
And one small design change. Can we put the toolbar (the rounded rectangles at the bottom right) be above the error/warnings panel?

2017-06-23 05:51 UTC, domoritz commented
Can you also merge the latest redux branch and see whether it causes any conflicts? Thanks! This looks fantastic.

2017-06-23 15:50 UTC, kanitw commented
> And one small design change. Can we put the toolbar (the rounded rectangles at the bottom right) be above the error/warnings panel?

Why don't we just move them to the same bar for the "parse" button?   All of these are relevant anyway.

2017-06-23 17:30 UTC, domoritz commented
> Why don't we just move them to the same bar for the "parse" button? All of these are relevant anyway.

I don't think there is enough room. But I'm happy to move them to the top of the right panel, above the visualization.

2017-06-28 01:30 UTC, domoritz commented
Can you rebase this branch onto `redux`?

2017-06-28 01:33 UTC, domoritz commented
To access the errors from the editor, we need: https://github.com/Microsoft/monaco-editor/issues/30. For now, we could use our own json schema validator but that's a little bit more work.

2017-06-28 01:43 UTC, domoritz requested changes
Please rebase and also catch errors in Vega specs. 

Other than that, it looks great.

2017-06-29 18:41 UTC, domoritz commented
Thanks for the update. Can you add a way to hide the error panel? Right now I can only resize it.

2017-07-02 21:52 UTC, domoritz commented
Looks good. One last issue. When I resize the warning panel and then parse a new spec, it resets the size.

2017-07-02 23:44 UTC, domoritz commented on src/components/renderer/renderer.js
> +        localStorage.setItem('splitPos', window.innerHeight * 0.6)
Please don't put the split size info in local storage because it will be invalid when the browser is resized in between refreshes.

2017-07-03 04:15 UTC, domoritz commented on src/actions/editor.js
> +export const SET_MODE = 'SET_MODE';
I don't think `SET_MODE ` is used anymore.

2017-07-03 04:16 UTC, merged